version: '3.2'
services:
  kbs:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.kbs
    image: trustee-registry.cn-hangzhou.cr.aliyuncs.com/instance/kbs:1.6.0
    command: [
      "/usr/local/bin/kbs",
      "--config-file",
      "/etc/kbs-config.toml",
    ]
    restart: always # keep the server running
    environment:
      RUST_LOG: debug
    ports:
      - "8080:8080"
    volumes:
      - ./kbs/data/kbs-storage:/opt/confidential-containers/kbs/repository:rw
      - ./kbs/config/public.pub:/opt/confidential-containers/kbs/user-keys/public.pub
      - ./kbs/config/docker-compose/kbs-config.toml:/etc/kbs-config.toml
      - ./kbs/config/docker-compose/policy.rego:/opt/confidential-containers/kbs/policy.rego
    depends_on:
      - as

  as:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.as-grpc
    image: trustee-registry.cn-hangzhou.cr.aliyuncs.com/instance/as:1.6.0
    ports:
      - "50004:50004"
    restart: always
    environment:
      RUST_LOG: debug
    volumes:
      - ./kbs/data/attestation-service:/opt/confidential-containers/attestation-service:rw
      - ./kbs/config/as-config.json:/etc/as-config.json:rw
      - ./kbs/config/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf:rw
    command: [
      "grpc-as",
      "--socket",
      "0.0.0.0:50004",
      "--config-file",
      "/etc/as-config.json"
    ]
    depends_on:
      - rvps

  as-restful:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.as-restful
    image: trustee-registry.cn-hangzhou.cr.aliyuncs.com/instance/as-restful:1.6.0
    ports:
      - "50005:50005"
    restart: always
    environment:
      RUST_LOG: debug
    volumes:
      - ./kbs/data/attestation-service:/opt/confidential-containers/attestation-service:rw
      - ./kbs/config/as-config.json:/etc/as-config.json:rw
      - ./kbs/config/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf:rw
    command: [
      "restful-as",
      "--socket",
      "0.0.0.0:50005",
      "--config-file",
      "/etc/as-config.json"
    ]
    depends_on:
      - rvps

  rvps:
    image: trustee-registry.cn-hangzhou.cr.aliyuncs.com/instance/rvps:1.6.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile.rvps
    restart: always # keep the server running
    ports:
      - "50003:50003"
    volumes:
      - ./kbs/data/reference-values:/opt/confidential-containers/attestation-service/reference_values:rw
      - ./kbs/config/rvps.json:/etc/rvps.json:rw
    command: [
      "rvps",
      "--address",
      "0.0.0.0:50003"
    ]

  # trustee-client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.trustee-client
  #   volumes:
  #     - ./../data/:/tmp/:rw
  #     - ./kbs/config/rvps.json:/etc/rvps.json:rw
  #   command: sh -c "cp /usr/local/bin/trustee-client /tmp/"

  tng:
    image: confidential-ai-registry.cn-shanghai.cr.aliyuncs.com/product/tng:1.0.2
    cap_add:
      - NET_ADMIN
    network_mode: host
    command:
      - tng
      - launch
      - --config-content
      - |
        {
          "add_ingress": [
            {
              "mapping": {
                "in": {
                  "host": "0.0.0.0",
                  "port": 9001
                },
                "out": {
                  "host": "0.0.0.0",
                  "port": 41000
                }
              },
              "verify": {
                "as_addr": "${TRUSTEE_AS_ADDR}",
                "policy_ids": [
                  "default"
                ]
              }
            }
          ]
        }
    # healthcheck:
    #   test: ["CMD-SHELL", "curl http://127.0.0.1:41000/tng/v1/healthcheck"]
    #   interval: 3s
    #   timeout: 5s
    #   start_period: 20s
    #   start_interval: 3s
    #   retries: 5
    depends_on:
      - as
      - as-restful